openapi: 3.0.1
info:
  title: 3d ingestion helpers
  description: External tools invocation to assist during 3d models upload
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8084
paths:
  /validations:
    post:
      operationId: post
      summary: Get validation results
      tags:
        - validations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postPayload'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation'
        400:
          $ref: '#/components/responses/badRequest'
        '5XX':
          $ref: '#/components/responses/unexpectedError'
components:
  responses:
    badRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    notFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    unexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    postPayload:
      type: object
      required:
        - path
      properties:
        path:
          type: string
    validation:
      type: object
      required:
        - validations
      properties:
        status:
          type: string
